name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23liq4RsgK5P9nu0Jn"
GITHUB_ID = "Ov23liq4RsgK5P9nu0Jn"
GITHUB_OWNER = "1061700625"
GITHUB_REPO = "myNavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://nav-1kf.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://nav-1kf.pages.dev"

